---
- name: Configure Apache and deploy website on Ubuntu
  hosts: web
  become: yes
  vars:
    web_root: /var/www/html
    src_index: "{{ web_src }}"

  tasks:

    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is running and enabled on boot
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create web root directory (if not exists)
      file:
        path: "{{ web_root }}"
        state: directory
        mode: '0755'

    - name: Copy index.html to Apache folder
      copy:
        src: "{{ src_index }}"
        dest: "{{ web_root }}/index.html"
        mode: '0644'
